### PR TITLE
PQT = 0 in setPromiscuous

### PR DESCRIPTION
**Pull request by Crsarmv7l**
Sets PQT to 0 in setPromiscuous(true)

### CODE REVIEW

**Comment by Crsarmv7l** [comment]
I included the bool for the two carriersense options for promiscuous that I mentioned in the discussion. If you are open to it I can submit both this and that as one pull request.

**Comment by jgromes** [comment]
Thanks for the contribution! I think the option for carrier sense can be added directly in this PR. Please make sure it is set to to `false` when calling `setPromiscuousMode` without arguments.

**Comment by Crsarmv7l** [comment]
> Thanks for the contribution! I think the option for carrier sense can be added directly in this PR. Please make sure it is set to to `false` when calling `setPromiscuousMode` without arguments.

Should be good to go, let me know if there are any issues. Thank you for your patience, willingness to help and acceptance of some small but nice to have changes!

**Comment by jgromes** [comment]
Merged, thank you for the contribution!

**Pull request merged**
