### PR TITLE
Fixes overload warning when building with ESP IDF

### PR DESCRIPTION
**Pull request by illysky**
Similar to previous fixes on overload on getRSSI - a fix was also needed on some of the sleep functions. 

Those were added.

### CODE REVIEW

**Comment by jgromes** [comment]
Thank you for this contribution! Could you also add doxygen comments to the .h files, similar to what was done for `getRSSI`?

```
    /*!
      \brief Gets recorded signal strength indicator.
      Overload with packet mode enabled for PhysicalLayer compatibility.
      \returns RSSI value in dBm.
    */
    float getRSSI();
```

**Comment by illysky** [comment]
Sure! Leave it with me

Best Regards

Kind Regards

Dominic Moffat
Electronic Design Director

Illysky Ltd
1 Field Rise, Ticehurst, East Sussex, TN5 7FH
+44 (0) 7732 885 372

This email and any files transmitted with it are confidential and intended
solely for the individual to whom it is addressed. Any views or opinions
presented are those of the author and do not necessarily represent those of
Illysky Ltd

**Comment by jgromes** [comment]
Since this has been left open for a while, I'm going to merge this as-is and add the doxygen comments afterwards.

Thanks for the contribution!

**Comment by illysky** [comment]
Hello! Apologies, few really busy weeks with work, thank you. If you need
anything else please let me know.

Kind Regards

Dominic Moffat
Electronic Design Director

Illysky Ltd
1 Field Rise, Ticehurst, East Sussex, TN5 7FH
+44 (0) 7732 885 372

This email and any files transmitted with it are confidential and intended
solely for the individual to whom it is addressed. Any views or opinions
presented are those of the author and do not necessarily represent those of
Illysky Ltd

**Comment by jgromes** [comment]
@illysky no worries, just something I wanted to scratch off the TODO list ;)

**Pull request merged**
