### PR TITLE
STM32 - use HardwareSerial instead of SoftwareSerial

### PR DESCRIPTION
**Pull request by mmrein**
Added support for STM32 based boards, using HardwareSerial instead of SoftwareSerial the same way as in https://github.com/jgromes/RadioLib/pull/39

### CODE REVIEW

**Comment by jgromes** [comment]
Thanks, were you able to test this with some wireless modules?

**Comment by mmrein** [comment]
Didn't test RF communication, but initialization was successfull with SX1261MB2BAS and RFM95 (both 868MHz) connected to so called BluePill board (STM32F103C8T6 cheap dev board) running official STM32duino core (https://github.com/stm32duino/Arduino_Core_STM32).

**Comment by jgromes** [comment]
OK, I'll merge this and try to figure out how to integrate STM32 into Travis.

Thanks for the PR!

**Comment by mmrein** [comment]
You're welcome, thanks for the library!

**Pull request merged**
