### PR TITLE
RF69 and SX127X new functions

### PR DESCRIPTION
**Pull request by cpainchaud**
- SX127X enable/disable BitSync
- RF69::enableContinuousModeBitSync()
- RF69::setOokFixedThreshold
- RF69::setOokFixedThreshold()

### CODE REVIEW

**Comment by jgromes** [comment]
Thanks - out of curiosity, what are the use cases of the proposed methods? Mainly the bit sync enable/disable methods.

**Comment by cpainchaud** [comment]
It has a lot of impacts on OOK signal (I am working on a Rflink/rtl433 esp)

**Comment by jgromes** [comment]
> It has a lot of impacts on OOK signal

I'm still not entirely sure what you mean. Were there issues with OOK? Or is it just something you needed in your application?

Sorry for taking a bit of time on this, I'm currently in the process of reworkign a lot of low-level stuff in the library.

**Comment by cpainchaud** [comment]
It is not an issue really it's just that BitSync I'll over process signal to match the bitrate timings. In my case I need to disable it sometimes

**Comment by jgromes** [comment]
Merged, thanks!

**Pull request merged**
