### PR TITLE
SX127X FSK Mode: transmit up to 256 bytes

### PR DESCRIPTION
**Pull request by justephens**
The datasheet describes an "on-the-fly" method of refilling the FIFO buffer when transmitting in FSK mode, which allows for FSK packets up to 256 bytes long. I made small tweaks to the `SX127X::transmit` method to handle this case.

I am not familiar `yield()`, but this implementation will capture control and just sit in a loop until all of a message has been pushed into the FIFO, which I suspect might not be fantastic.

### CODE REVIEW

**Comment by jgromes** [comment]
This was done previously for CC1101 in https://github.com/jgromes/RadioLib/pull/279, in a very similar way (waiting inside `startTransmit` for FIFO to be sufficiently empty to add more bytes).

> this implementation will capture control and just sit in a loop until all of a message has been pushed into the FIFO, which I suspect might not be fantastic.

You're absolutely right: that's the general issue I see with this approach. It basically turns the non-blocking `startTransmit` method into a blocking one, since it has to wait until some data is transmitted. For low datarates, that can take quite some time.

However, a more generic approach to handling packets larger than FIFO is being discussed in https://github.com/jgromes/RadioLib/issues/399 and (primarily) https://github.com/jgromes/RadioLib/issues/201

**Comment by justephens** [comment]
Thanks for pointing me to those issues (which I probably should have searched for myself, oops). I have a break next week and will try my hand at implementing the feature in a proper way then.

Any guidance on how to implement the feature in way friendly to multiple chips?

**Comment by jgromes** [comment]
Take a look at other methods that are shared accross the modules, for example `transmit()` method. It has a pure virtual method in `PhysicalLayer` class, which is then implement in all classes derived from `PhysicalLayer`: `SX127x`, `CC1101` etc., so then the `transmit` method for any module may be called by calling its `PhysicalLayer` interface.

**Comment by jgromes** [comment]
Since there was no progress on this for quite some time, and Stream mode is now supported for SX127x modules, I'm closing this PR - sorry about that @justephens.

**Pull request closed without merging**
