### PR TITLE
github: Add Tock CI

### PR DESCRIPTION
**Pull request by alistair23**

### CODE REVIEW

**Comment by jgromes** [comment]
I tried to manually run these commands on Ubuntu 22.04, and it seems there some dependency missing:

```
jgromes@jgromes-Ubuntu2204:~/repos/RadioLib/examples/NonArduino/Tock$ ./build.sh 
/bin/sh: 1: elf2tab: not found
Trying to update elf2tab to >= 0.7.0
make: cargo: No such file or directory
/bin/sh: 1: elf2tab: not found
../Configuration.mk:132: *** Failed to automatically update elf2tab, please update manually elf2tab to >= 0.7.0.  Stop.
```

**Comment by alistair23** [comment]
I added a step to install `elf2tab`

**Comment by jgromes** [comment]
```
jgromes@jgromes-Ubuntu2204:~$ cargo install elf2tab
Command 'cargo' not found, but can be installed with:
sudo snap install rustup  # version 1.24.3, or
sudo apt  install cargo   # version 0.67.1+ds0ubuntu0.libgit2-0ubuntu0.22.04.2
See 'snap info rustup' for additional versions.
```

Seems like Ubuntu also doesn't ship cargo with by default. Installing manually with apt and then trying to install elf2tab leads to:

```
error: failed to compile `elf2tab v0.11.0`, intermediate artifacts can be found at `/tmp/cargo-installZRlsHe`
Caused by:
  package `clap_builder v4.4.1` cannot be built because it requires rustc 1.70.0 or newer, while the currently active rustc version is 1.66.1
  Try re-running cargo install with `--locked`
```

**Comment by jgromes** [comment]
Merged, thanks!

**Pull request merged**
