### PR TITLE
[SX127x] fix DIO register mapping

### PR DESCRIPTION
**Pull request by caveman99**
this fixes https://github.com/jgromes/RadioLib/issues/1244

### CODE REVIEW

**Comment by jgromes** [comment]
Well that's a rather silly mistake isn't it ... fortunately these new IRQ methods are not being used internally by SX127x or LoRaWAN (yet), so I don't think we need to push this as another hotfix. Regardless, thank you for the fix!

**Comment by caveman99** [comment]
unfortunately the setting of the registers is used in startReceive() https://github.com/jgromes/RadioLib/blob/5a9ff5a4912f87918390348c8caa54ea8a6afada/src/modules/SX127x/SX127x.cpp#L392C1-L401C26 

After upgrading to 7.0.1 we were seeing RX not triggering the IRQ any more. It does not warrant a new release, we can just track the commit point for our builds, and i still have to check if this is really the fix for those problems. Test node is building as i write :-)

**Comment by jgromes** [comment]
I see - that is a significant issue then. I will push this as 7.0.2 then, otherwise it will be broken for everyone else using 7.0.1 and not tracking the latest commit.

**Comment by caveman99** [comment]
I can confirm, operating two TLora 2.1-1.6 with SX1276 alongside each other, with the fix RX is fine, without it does not trigger the IRQ.

**Comment by jgromes** [comment]
FYI @caveman99 released as 7.0.2, hopefully that will be the last hotfix for a while ...

**Comment by caveman99** [comment]
Thanks a lot for the quick response! :-) I hope so too.

**Pull request merged**
