### PR TITLE
Modify (SX1262.h, SX1262.cpp): remove tcxoVoltage from begin, because…

### PR DESCRIPTION
**Pull request by RJSDevel**
remove tcxoVoltage from begin, because it isn't support in SX1262 and LLCC68, override setTCXO by the same cause

### CODE REVIEW

**Comment by jgromes** [comment]
How did you arrive at the conclusion that TCXO isn't supported by SX1262 and LLCC68? Both SX1262 and LLCC68 datasheets say otherwise, see for example chapter 4.1.4 4 TCXO Control Block in LLCC68 datasheet.

Your particular LLCC68 module might be using XTAL instead of TCXO, but that's not a reason to drop TCXO support for every LLCC68 module.

**Comment by RJSDevel** [comment]
https://github.com/jgromes/RadioLib/issues/89#issuecomment-565008040

**Comment by RJSDevel** [comment]
If it supports TCXO , then add any information to docs that it sometimes doesn't support it, because I've spent about week to find that

**Comment by jgromes** [comment]
> it sometimes doesn't support it

Unforunately it's a bit more complicated - all SX126x transceivers (LLCC68 included) support TCXO. It's up to whoever is building the module using the transceiver whether he decides to use TCXO or not. By default, RadioLib assumes TCXO to be used, because from what I've seen, modules with TCXO are more common. 

If I were to set the default to XTAL being used, the same issues would appear on TCXO-equipped modules. I can add even more information to the already quite extensive documentation, but ultimately it's up to the user to read the docs, and then configure RadioLib to match the hardware - same thing would apply if you were to for example select an incorrect SPI bus, not much I can do to stop you from doing that.

**Pull request closed without merging**
