### PR TITLE
Introduce asynchronous reception and transmission for CC1101

### PR DESCRIPTION
**Pull request by obones**
This allows using the asynchronous mode from the CC110, should a project need it for "raw" transmissions. This is most useful in projects that do timing and packet analysis by themselves, such as RFLink32 for instance.

### CODE REVIEW

**Comment by jgromes** [comment]
Thank you for the contribution!

One point though: this introduces some code duplication. Overall, I believe the only meaningful difference between the current `directMode` and the new `asyncDirectMode` is one value in `RADIOLIB_CC1101_REG_PKTCTRL0`.

I think it would be better to add a parameter to `directMode(bool async = false)`, so that it defaults to the current synchronous direct mode (since that's supported on other modules as well).

The public API methods `transmitDirectAsync`/`receiveDirectAsync` should remain.

**Comment by obones** [comment]
> I believe the only meaningful difference between the current `directMode` and the new `asyncDirectMode` is one value in `RADIOLIB_CC1101_REG_PKTCTRL0`.

Well, it's not just this one, there is also a different mapping for the GD0 pin: `CC1101_REG_IOCFG0` is set to `CC1101_GDOX_SERIAL_DATA_ASYNC`

But I agree that there is quite a bit of code duplication, most noticeably in `transmitDirectAsync`. Wouldn't it be better if I was to change my PR to get this final result:

image

I believe this would remove all code duplication.

**Comment by jgromes** [comment]
Unfortunately we can't change the signatures of `transmitDirect`/`receiveDirect`, because they implement pure virtual methods from `PhysicalLayer`.

**Comment by obones** [comment]
Yes, I know that, but I'm not suggesting to change those, I'm just adding a new "overload" with an additional parameter called `sync` that gets called by the `override` ones. Here is an example with `receiveDirect`:

```c
int16_t CC1101::receiveDirect() {
  return receiveDirect(true);
}

int16_t CC1101::receiveDirectAsync() {
  return receiveDirect(false);
}

int16_t CC1101::receiveDirect(bool sync) {
  // set RF switch (if present)
  _mod->setRfSwitchState(HIGH, LOW);

  // activate direct mode
  int16_t state = directMode(sync);
  RADIOLIB_ASSERT(state);

  // start receiving
  SPIsendCommand(CC1101_CMD_RX);
  return(ERR_NONE);
}
```

This compiles and runs just fine, `receiveDirect()` is left as is in the header file, while `receiveDirect(bool)` is added to the `protected` section at the bottom, near `directMode()`

**Comment by jgromes** [comment]
Ah, I see - in that case it's OK.

Was this tested with hardware?

**Comment by obones** [comment]
> Was this tested with hardware?

Yes, I have it running here just fine, as used by my yet to be published work on the [RFLink32](https://github.com/cpainchaud/RFLink32) project

**Comment by jgromes** [comment]
Seems the CI failed on `ERR_NONE` being undefined. This changed in the 5.0.0 release, now it's `RADIOLIB_ERR_NONE`.

Please double check you're using the latest library version.

**Comment by obones** [comment]
I have pushed the discussed changes, I believe this is now just fine.

**Comment by jgromes** [comment]
Looking good now - merged, thanks for the contribution!

**Pull request merged**
