### PR TITLE
[LoRaWAN] Resolve warnings, fix bugs for fixed bands

### PR DESCRIPTION
**Pull request by jgromes**
Found when manually checking LoRaWAN builds for platforms that were previously disabled in CI. These were mostly unused variables, however, random selection of join DR was also unused, so maybe that was a mistake?

cc @StevenCellist

### CODE REVIEW

**Comment by StevenCellist** [comment]
Ah, the `drJR` is now incorrectly 'forgotten' indeed. That function was using internal MAC commands which was a mistake (it overwrote the active state with the default channels), but apparently I also removed the MAC command to configure the required join-datarate. Will look at a fix.

**Comment by jgromes** [comment]
@StevenCellist thanks! You should be able to push to this branch, so feel free to add the fix here.

**Comment by StevenCellist** [comment]
Turns out that there was some more stuff to do: there was a bug in processing the CFList that caused the Tx power to drop by 14dBm upon a join, and not all scenarios w.r.t. selecting an initial datarate were handled. Changes tested on EU868/ABP and US915/OTAA.

**Comment by StevenCellist** [comment]
Hold on a minute and I got one small thing as well :)

**Comment by StevenCellist** [comment]
Good to go now from my perspective

**Comment by jgromes** [comment]
Perfect, thanks for the help!

**Pull request merged**
