### PR TITLE
Enabling ACK support for LoRaWAN frames.

### PR DESCRIPTION
**Pull request by jgamage91**
To the best of my knowledge, there isn't yet support to send frames with a request for ACK from the network server. This pull request makes an effort to enable an ACK request per frame by calling `node.uplink(strUp, 10, true);` from user space. This does not break existing functionality. I have tested this using the SX1262 radio and the Actility Thingpark Network server. The functionality seems to be working well.

Acknowledgement: I thank Jansen Christian Liando for his advice on how to enable this. 

As always, I welcome feedback.

### CODE REVIEW

**Comment by StevenCellist** [comment]
Hi @jgamage91, before we do any double work... I am at almost 100% LoRaWAN v1.1 compatibility on a fork. Which includes bi-directional confirmed frames and MUCH more. You're welcome to do some testing so we can get it in here soon! Let me know :)

**Comment by jgamage91** [comment]
> Hi @jgamage91, before we do any double work... I am at almost 100% LoRaWAN v1.1 compatibility on a fork. Which includes bi-directional confirmed frames and MUCH more. You're welcome to do some testing so we can get it in here soon! Let me know :)

Oh I understand. Thanks great to hear! I am happy to do some testing when you release it. So should I close this for now?

**Comment by StevenCellist** [comment]
You can find the most recent version here:
https://github.com/StevenCellist/RadioLib/tree/bands_adr_mac
Some gotchas are listed here:
https://github.com/jgromes/RadioLib/issues/821

If you have an SX126x board, it would be great if you can check out the code. One more gotcha that you'll need to watch out for: after joining, you'll need a `delay(5000)` in your main code as something there is not working very nicely yet.
If you have an SX127x, feel free to dig into the Rx windows and see if you can implement/copy the SX126x logic to get RxSingle with timeout working.. ;)

In case of problems, please enable a debug build and maybe post it as an issue on the fork with some sample output

**Comment by jgamage91** [comment]
> You can find the most recent version here: https://github.com/StevenCellist/RadioLib/tree/bands_adr_mac Some gotchas are listed here: #821
> 
> If you have an SX126x board, it would be great if you can check out the code. One more gotcha that you'll need to watch out for: after joining, you'll need a `delay(5000)` in your main code as something there is not working very nicely yet. If you have an SX127x, feel free to dig into the Rx windows and see if you can implement/copy the SX126x logic to get RxSingle with timeout working.. ;)
> 
> In case of problems, please enable a debug build and maybe post it as an issue on the fork with some sample output


I did a run of your code on the SX1262 + ESP32. The timeout & downlinks seem to be working on on the first tests. My debug log below:

`---- Opened the serial port /dev/ttyACM0 ----
uplink sent successfully pktCnt: 1
NO GPS FIX #0
 Downlink timeout!




uplink sent successfully pktCnt: 2
NO GPS FIX #1
 Downlink timeout!




uplink sent successfully pktCnt: 3
NO GPS FIX #2
 Downlink timeout!




uplink sent successfully pktCnt: 4
NO GPS FIX #3
 Downlink timeout!




uplink sent successfully pktCnt: 5
NO GPS FIX #4
 Downlink timeout!



**[I send a downlink thru network server here]**
uplink sent successfully pktCnt: 6
NO GPS FIX #5
Downlink Received!
[Downlink] Data:                5tm�
[Downlink] RSSI:                -39.00 dBm
[Downlink] SNR:         8.25 dB
[Downlink] Frequency error:     142.41 Hz




uplink sent successfully pktCnt: 7
NO GPS FIX #6
Downlink Received!
[Downlink] Data:                ��-��S
[Downlink] RSSI:                -40.00 dBm
[Downlink] SNR:         8.25 dB
[Downlink] Frequency error:     140.47 Hz




uplink sent successfully pktCnt: 8
NO GPS FIX #7
Downlink Received!
[Downlink] Data:                dc      ����
[Downlink] RSSI:                -41.00 dBm
[Downlink] SNR:         8.25 dB
[Downlink] Frequency error:     142.41 Hz




uplink sent successfully pktCnt: 9
NO GPS FIX #8
Downlink Received!
[Downlink] Data:                ZA��W
                                     �
[Downlink] RSSI:                -40.00 dBm
[Downlink] SNR:         7.75 dB
[Downlink] Frequency error:     144.34 Hz




uplink sent successfully pktCnt: 10
NO GPS FIX #9
Downlink Received!
[Downlink] Data:                E�h���
[Downlink] RSSI:                -39.00 dBm
[Downlink] SNR:         8.25 dB
[Downlink] Frequency error:     144.34 Hz




uplink sent successfully pktCnt: 11
NO GPS FIX #10
Downlink Received!
[Downlink] Data:                ����l
[Downlink] RSSI:                -41.00 dBm
[Downlink] SNR:         7.75 dB
[Downlink] Frequency error:     144.34 Hz




uplink sent successfully pktCnt: 12
NO GPS FIX #11
Downlink Received!
[Downlink] Data:                �6��
[Downlink] RSSI:                -41.00 dBm
[Downlink] SNR:         8.00 dB
[Downlink] Frequency error:     146.28 Hz




uplink sent successfully pktCnt: 13
NO GPS FIX #12
Downlink Received!
[Downlink] Data:                r
2ҫ
[Downlink] RSSI:                -41.00 dBm
[Downlink] SNR:         8.50 dB
[Downlink] Frequency error:     148.22 Hz




uplink sent successfully pktCnt: 14
NO GPS FIX #13
 Downlink timeout!




uplink sent successfully pktCnt: 15
NO GPS FIX #14
 Downlink timeout!




uplink sent successfully pktCnt: 16
NO GPS FIX #15`

Can I know what you meant by "SX126x logic to get RxSingle with timeout working"?

**Comment by jgromes** [comment]
@jgamage91 #867 was just merged, which includes ACK support among major revwork of the LoRaWAN implementation, so unfortunately I have to close this one now. We're still looking for people willing to test it before the next release though, so if you have some time for that, it would be very much appreciated.

**Pull request closed without merging**
